CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP(6),
    fecha_modificacion TIMESTAMP(6),
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    prioridad INTEGER NOT NULL,
    rol VARCHAR(255),
    CONSTRAINT usuario_prioridad_check CHECK (prioridad >= 1 AND prioridad <= 10),
    CONSTRAINT usuario_rol_check CHECK (rol IN ('USER', 'ADMIN'))
);

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP(6),
    fecha_modificacion TIMESTAMP(6),
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP(6),
    fecha_modificacion TIMESTAMP(6),
    descripcion VARCHAR(255) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_post_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
);

CREATE TABLE post_categoria (
    post_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    PRIMARY KEY (post_id, categoria_id),
    CONSTRAINT fk_post_categoria_post
        FOREIGN KEY (post_id)
        REFERENCES post(id),
    CONSTRAINT fk_post_categoria_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id)
);

CREATE TABLE comentario_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP(6),
    fecha_modificacion TIMESTAMP(6),
    comentario VARCHAR(255) NOT NULL,
    post_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_comentario_post
        FOREIGN KEY (post_id)
        REFERENCES post(id),
    CONSTRAINT fk_comentario_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
);
